# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_306b.ui'
#
# Created: Fri Apr 09 12:54:22 2021
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1030, 405)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1030, 405))
        MainWindow.setMaximumSize(QtCore.QSize(1030, 405))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sc_icon_16x16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.taskBox = QtGui.QGroupBox(self.centralwidget)
        self.taskBox.setGeometry(QtCore.QRect(10, 10, 481, 271))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.taskBox.setFont(font)
        self.taskBox.setObjectName(_fromUtf8("taskBox"))
        self.effectlabel = QtGui.QLabel(self.taskBox)
        self.effectlabel.setGeometry(QtCore.QRect(340, 210, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.effectlabel.setFont(font)
        self.effectlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.effectlabel.setObjectName(_fromUtf8("effectlabel"))
        self.effect_result = QtGui.QLabel(self.taskBox)
        self.effect_result.setGeometry(QtCore.QRect(250, 230, 221, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect_result.sizePolicy().hasHeightForWidth())
        self.effect_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.effect_result.setFont(font)
        self.effect_result.setFrameShape(QtGui.QFrame.Box)
        self.effect_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.effect_result.setText(_fromUtf8(""))
        self.effect_result.setAlignment(QtCore.Qt.AlignCenter)
        self.effect_result.setObjectName(_fromUtf8("effect_result"))
        self.label_1 = QtGui.QLabel(self.taskBox)
        self.label_1.setGeometry(QtCore.QRect(0, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.plus_sign_2 = QtGui.QLabel(self.taskBox)
        self.plus_sign_2.setGeometry(QtCore.QRect(230, 110, 16, 16))
        self.plus_sign_2.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_2.setObjectName(_fromUtf8("plus_sign_2"))
        self.equal_sign = QtGui.QLabel(self.taskBox)
        self.equal_sign.setGeometry(QtCore.QRect(400, 110, 16, 16))
        self.equal_sign.setAlignment(QtCore.Qt.AlignCenter)
        self.equal_sign.setObjectName(_fromUtf8("equal_sign"))
        self.resultlabel = QtGui.QLabel(self.taskBox)
        self.resultlabel.setGeometry(QtCore.QRect(10, 210, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultlabel.setFont(font)
        self.resultlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultlabel.setObjectName(_fromUtf8("resultlabel"))
        self.totalDM = QtGui.QLabel(self.taskBox)
        self.totalDM.setGeometry(QtCore.QRect(430, 100, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalDM.sizePolicy().hasHeightForWidth())
        self.totalDM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.totalDM.setFont(font)
        self.totalDM.setFrameShape(QtGui.QFrame.Box)
        self.totalDM.setFrameShadow(QtGui.QFrame.Sunken)
        self.totalDM.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDM.setObjectName(_fromUtf8("totalDM"))
        self.inputDM = QtGui.QSpinBox(self.taskBox)
        self.inputDM.setGeometry(QtCore.QRect(260, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputDM.setFont(font)
        self.inputDM.setFrame(True)
        self.inputDM.setAlignment(QtCore.Qt.AlignCenter)
        self.inputDM.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.inputDM.setMinimum(-99)
        self.inputDM.setMaximum(99)
        self.inputDM.setObjectName(_fromUtf8("inputDM"))
        self.inputchar = QtGui.QSpinBox(self.taskBox)
        self.inputchar.setGeometry(QtCore.QRect(30, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputchar.setFont(font)
        self.inputchar.setFrame(True)
        self.inputchar.setAlignment(QtCore.Qt.AlignCenter)
        self.inputchar.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.inputchar.setMinimum(0)
        self.inputchar.setMaximum(21)
        self.inputchar.setProperty("value", 7)
        self.inputchar.setObjectName(_fromUtf8("inputchar"))
        self.plus_sign_1 = QtGui.QLabel(self.taskBox)
        self.plus_sign_1.setGeometry(QtCore.QRect(150, 110, 16, 16))
        self.plus_sign_1.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_1.setObjectName(_fromUtf8("plus_sign_1"))
        self.inputlevel = QtGui.QSpinBox(self.taskBox)
        self.inputlevel.setGeometry(QtCore.QRect(180, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputlevel.setFont(font)
        self.inputlevel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputlevel.setMinimum(-3)
        self.inputlevel.setMaximum(5)
        self.inputlevel.setSingleStep(1)
        self.inputlevel.setObjectName(_fromUtf8("inputlevel"))
        self.die1Label = QtGui.QLabel(self.taskBox)
        self.die1Label.setGeometry(QtCore.QRect(300, 150, 48, 48))
        self.die1Label.setText(_fromUtf8(""))
        self.die1Label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/die1_0.png")))
        self.die1Label.setObjectName(_fromUtf8("die1Label"))
        self.die3Label = QtGui.QLabel(self.taskBox)
        self.die3Label.setGeometry(QtCore.QRect(420, 150, 48, 48))
        self.die3Label.setText(_fromUtf8(""))
        self.die3Label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/die2_0.png")))
        self.die3Label.setObjectName(_fromUtf8("die3Label"))
        self.die2Label = QtGui.QLabel(self.taskBox)
        self.die2Label.setGeometry(QtCore.QRect(350, 150, 48, 48))
        self.die2Label.setText(_fromUtf8(""))
        self.die2Label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/die2_0.png")))
        self.die2Label.setObjectName(_fromUtf8("die2Label"))
        self.rollBox = QtGui.QGroupBox(self.taskBox)
        self.rollBox.setGeometry(QtCore.QRect(10, 140, 281, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rollBox.setFont(font)
        self.rollBox.setObjectName(_fromUtf8("rollBox"))
        self.roll2D_Button = QtGui.QPushButton(self.rollBox)
        self.roll2D_Button.setGeometry(QtCore.QRect(10, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.roll2D_Button.setFont(font)
        self.roll2D_Button.setFlat(False)
        self.roll2D_Button.setObjectName(_fromUtf8("roll2D_Button"))
        self.rollBoon_Button = QtGui.QPushButton(self.rollBox)
        self.rollBoon_Button.setGeometry(QtCore.QRect(70, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollBoon_Button.setFont(font)
        self.rollBoon_Button.setFlat(False)
        self.rollBoon_Button.setObjectName(_fromUtf8("rollBoon_Button"))
        self.rollBane_Button = QtGui.QPushButton(self.rollBox)
        self.rollBane_Button.setGeometry(QtCore.QRect(130, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollBane_Button.setFont(font)
        self.rollBane_Button.setFlat(False)
        self.rollBane_Button.setObjectName(_fromUtf8("rollBane_Button"))
        self.rollD66_Button = QtGui.QPushButton(self.rollBox)
        self.rollD66_Button.setGeometry(QtCore.QRect(210, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rollD66_Button.setFont(font)
        self.rollD66_Button.setObjectName(_fromUtf8("rollD66_Button"))
        self.plus_sign_5 = QtGui.QLabel(self.taskBox)
        self.plus_sign_5.setGeometry(QtCore.QRect(320, 110, 16, 16))
        self.plus_sign_5.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_5.setObjectName(_fromUtf8("plus_sign_5"))
        self.chainedDM = QtGui.QLabel(self.taskBox)
        self.chainedDM.setGeometry(QtCore.QRect(360, 100, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chainedDM.sizePolicy().hasHeightForWidth())
        self.chainedDM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chainedDM.setFont(font)
        self.chainedDM.setFrameShape(QtGui.QFrame.Box)
        self.chainedDM.setFrameShadow(QtGui.QFrame.Sunken)
        self.chainedDM.setAlignment(QtCore.Qt.AlignCenter)
        self.chainedDM.setObjectName(_fromUtf8("chainedDM"))
        self.charmod = QtGui.QLabel(self.taskBox)
        self.charmod.setGeometry(QtCore.QRect(110, 100, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charmod.sizePolicy().hasHeightForWidth())
        self.charmod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charmod.setFont(font)
        self.charmod.setFrameShape(QtGui.QFrame.Box)
        self.charmod.setFrameShadow(QtGui.QFrame.Sunken)
        self.charmod.setAlignment(QtCore.Qt.AlignCenter)
        self.charmod.setObjectName(_fromUtf8("charmod"))
        self.dieRange = QtGui.QLabel(self.taskBox)
        self.dieRange.setGeometry(QtCore.QRect(300, 130, 101, 20))
        self.dieRange.setText(_fromUtf8(""))
        self.dieRange.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/die_range.png")))
        self.dieRange.setAlignment(QtCore.Qt.AlignCenter)
        self.dieRange.setObjectName(_fromUtf8("dieRange"))
        self.selChained = QtGui.QCheckBox(self.taskBox)
        self.selChained.setGeometry(QtCore.QRect(340, 100, 16, 17))
        self.selChained.setText(_fromUtf8(""))
        self.selChained.setObjectName(_fromUtf8("selChained"))
        self.difflabel = QtGui.QLabel(self.taskBox)
        self.difflabel.setGeometry(QtCore.QRect(30, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.difflabel.setFont(font)
        self.difflabel.setAlignment(QtCore.Qt.AlignCenter)
        self.difflabel.setObjectName(_fromUtf8("difflabel"))
        self.selDiff = QtGui.QComboBox(self.taskBox)
        self.selDiff.setGeometry(QtCore.QRect(10, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selDiff.setFont(font)
        self.selDiff.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selDiff.setEditable(False)
        self.selDiff.setMaxVisibleItems(11)
        self.selDiff.setMaxCount(11)
        self.selDiff.setMinimumContentsLength(0)
        self.selDiff.setObjectName(_fromUtf8("selDiff"))
        self.inputtasks = QtGui.QSpinBox(self.taskBox)
        self.inputtasks.setGeometry(QtCore.QRect(180, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputtasks.setFont(font)
        self.inputtasks.setFrame(True)
        self.inputtasks.setAlignment(QtCore.Qt.AlignCenter)
        self.inputtasks.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.inputtasks.setMinimum(1)
        self.inputtasks.setMaximum(5)
        self.inputtasks.setObjectName(_fromUtf8("inputtasks"))
        self.numTasksLabel = QtGui.QLabel(self.taskBox)
        self.numTasksLabel.setGeometry(QtCore.QRect(160, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numTasksLabel.setFont(font)
        self.numTasksLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numTasksLabel.setObjectName(_fromUtf8("numTasksLabel"))
        self.selTimeframe = QtGui.QComboBox(self.taskBox)
        self.selTimeframe.setGeometry(QtCore.QRect(250, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selTimeframe.setFont(font)
        self.selTimeframe.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selTimeframe.setEditable(False)
        self.selTimeframe.setMaxVisibleItems(10)
        self.selTimeframe.setMaxCount(10)
        self.selTimeframe.setMinimumContentsLength(0)
        self.selTimeframe.setObjectName(_fromUtf8("selTimeframe"))
        self.selNewTimeframe = QtGui.QComboBox(self.taskBox)
        self.selNewTimeframe.setGeometry(QtCore.QRect(370, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selNewTimeframe.setFont(font)
        self.selNewTimeframe.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selNewTimeframe.setEditable(False)
        self.selNewTimeframe.setMaxVisibleItems(10)
        self.selNewTimeframe.setMaxCount(10)
        self.selNewTimeframe.setMinimumContentsLength(0)
        self.selNewTimeframe.setObjectName(_fromUtf8("selNewTimeframe"))
        self.timeframeLabel_1 = QtGui.QLabel(self.taskBox)
        self.timeframeLabel_1.setGeometry(QtCore.QRect(260, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeframeLabel_1.setFont(font)
        self.timeframeLabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.timeframeLabel_1.setObjectName(_fromUtf8("timeframeLabel_1"))
        self.timeframeLabel_2 = QtGui.QLabel(self.taskBox)
        self.timeframeLabel_2.setGeometry(QtCore.QRect(370, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeframeLabel_2.setFont(font)
        self.timeframeLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.timeframeLabel_2.setObjectName(_fromUtf8("timeframeLabel_2"))
        self.tasktimeLabel = QtGui.QLabel(self.taskBox)
        self.tasktimeLabel.setGeometry(QtCore.QRect(120, 210, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tasktimeLabel.setFont(font)
        self.tasktimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tasktimeLabel.setObjectName(_fromUtf8("tasktimeLabel"))
        self.tasktime_result = QtGui.QLabel(self.taskBox)
        self.tasktime_result.setGeometry(QtCore.QRect(90, 230, 141, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tasktime_result.sizePolicy().hasHeightForWidth())
        self.tasktime_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tasktime_result.setFont(font)
        self.tasktime_result.setFrameShape(QtGui.QFrame.Box)
        self.tasktime_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.tasktime_result.setText(_fromUtf8(""))
        self.tasktime_result.setAlignment(QtCore.Qt.AlignCenter)
        self.tasktime_result.setObjectName(_fromUtf8("tasktime_result"))
        self.label_2 = QtGui.QLabel(self.taskBox)
        self.label_2.setGeometry(QtCore.QRect(100, 80, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.taskBox)
        self.label_3.setGeometry(QtCore.QRect(160, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.taskBox)
        self.label_4.setGeometry(QtCore.QRect(260, 80, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.taskBox)
        self.label_5.setGeometry(QtCore.QRect(320, 80, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.taskBox)
        self.label_6.setGeometry(QtCore.QRect(410, 80, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.rollresult = QtGui.QLabel(self.taskBox)
        self.rollresult.setGeometry(QtCore.QRect(20, 230, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollresult.sizePolicy().hasHeightForWidth())
        self.rollresult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rollresult.setFont(font)
        self.rollresult.setFrameShape(QtGui.QFrame.Box)
        self.rollresult.setFrameShadow(QtGui.QFrame.Sunken)
        self.rollresult.setText(_fromUtf8(""))
        self.rollresult.setAlignment(QtCore.Qt.AlignCenter)
        self.rollresult.setObjectName(_fromUtf8("rollresult"))
        self.outcomeBox = QtGui.QGroupBox(self.centralwidget)
        self.outcomeBox.setGeometry(QtCore.QRect(690, 10, 331, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setBold(True)
        font.setWeight(75)
        self.outcomeBox.setFont(font)
        self.outcomeBox.setObjectName(_fromUtf8("outcomeBox"))
        self.mpl = MplWidget(self.outcomeBox)
        self.mpl.setGeometry(QtCore.QRect(0, 10, 331, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setBold(True)
        font.setWeight(75)
        self.mpl.setFont(font)
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.brandlabel = QtGui.QLabel(self.centralwidget)
        self.brandlabel.setGeometry(QtCore.QRect(830, 310, 171, 31))
        self.brandlabel.setText(_fromUtf8(""))
        self.brandlabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/shonner_brand.png")))
        self.brandlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.brandlabel.setObjectName(_fromUtf8("brandlabel"))
        self.damageBox = QtGui.QGroupBox(self.centralwidget)
        self.damageBox.setGeometry(QtCore.QRect(10, 290, 661, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setBold(True)
        font.setWeight(75)
        self.damageBox.setFont(font)
        self.damageBox.setObjectName(_fromUtf8("damageBox"))
        self.inputdice = QtGui.QSpinBox(self.damageBox)
        self.inputdice.setGeometry(QtCore.QRect(390, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputdice.setFont(font)
        self.inputdice.setFrame(True)
        self.inputdice.setAlignment(QtCore.Qt.AlignCenter)
        self.inputdice.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.inputdice.setMinimum(1)
        self.inputdice.setMaximum(99)
        self.inputdice.setObjectName(_fromUtf8("inputdice"))
        self.Dicelabel = QtGui.QLabel(self.damageBox)
        self.Dicelabel.setGeometry(QtCore.QRect(390, 10, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Dicelabel.setFont(font)
        self.Dicelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Dicelabel.setObjectName(_fromUtf8("Dicelabel"))
        self.damage_Button = QtGui.QPushButton(self.damageBox)
        self.damage_Button.setGeometry(QtCore.QRect(440, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.damage_Button.setFont(font)
        self.damage_Button.setFlat(False)
        self.damage_Button.setObjectName(_fromUtf8("damage_Button"))
        self.destructive_Button = QtGui.QPushButton(self.damageBox)
        self.destructive_Button.setGeometry(QtCore.QRect(440, 40, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.destructive_Button.setFont(font)
        self.destructive_Button.setFlat(False)
        self.destructive_Button.setObjectName(_fromUtf8("destructive_Button"))
        self.inputDamageDM = QtGui.QSpinBox(self.damageBox)
        self.inputDamageDM.setGeometry(QtCore.QRect(500, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputDamageDM.setFont(font)
        self.inputDamageDM.setFrame(True)
        self.inputDamageDM.setAlignment(QtCore.Qt.AlignCenter)
        self.inputDamageDM.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.inputDamageDM.setMinimum(-99)
        self.inputDamageDM.setMaximum(99)
        self.inputDamageDM.setObjectName(_fromUtf8("inputDamageDM"))
        self.plus_sign_3 = QtGui.QLabel(self.damageBox)
        self.plus_sign_3.setGeometry(QtCore.QRect(480, 40, 16, 16))
        self.plus_sign_3.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_3.setObjectName(_fromUtf8("plus_sign_3"))
        self.damageDMlabel = QtGui.QLabel(self.damageBox)
        self.damageDMlabel.setGeometry(QtCore.QRect(510, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.damageDMlabel.setFont(font)
        self.damageDMlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.damageDMlabel.setObjectName(_fromUtf8("damageDMlabel"))
        self.totalDamagelabel = QtGui.QLabel(self.damageBox)
        self.totalDamagelabel.setGeometry(QtCore.QRect(610, 10, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalDamagelabel.setFont(font)
        self.totalDamagelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalDamagelabel.setObjectName(_fromUtf8("totalDamagelabel"))
        self.totalDamage = QtGui.QLabel(self.damageBox)
        self.totalDamage.setGeometry(QtCore.QRect(600, 30, 51, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalDamage.sizePolicy().hasHeightForWidth())
        self.totalDamage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.totalDamage.setFont(font)
        self.totalDamage.setFrameShape(QtGui.QFrame.Box)
        self.totalDamage.setFrameShadow(QtGui.QFrame.Sunken)
        self.totalDamage.setText(_fromUtf8(""))
        self.totalDamage.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDamage.setObjectName(_fromUtf8("totalDamage"))
        self.effect_damage = QtGui.QLabel(self.damageBox)
        self.effect_damage.setGeometry(QtCore.QRect(560, 30, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect_damage.sizePolicy().hasHeightForWidth())
        self.effect_damage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.effect_damage.setFont(font)
        self.effect_damage.setFrameShape(QtGui.QFrame.Box)
        self.effect_damage.setFrameShadow(QtGui.QFrame.Sunken)
        self.effect_damage.setText(_fromUtf8(""))
        self.effect_damage.setAlignment(QtCore.Qt.AlignCenter)
        self.effect_damage.setObjectName(_fromUtf8("effect_damage"))
        self.plus_sign_4 = QtGui.QLabel(self.damageBox)
        self.plus_sign_4.setGeometry(QtCore.QRect(540, 40, 16, 16))
        self.plus_sign_4.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_4.setObjectName(_fromUtf8("plus_sign_4"))
        self.effectlabel_2 = QtGui.QLabel(self.damageBox)
        self.effectlabel_2.setGeometry(QtCore.QRect(560, 10, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.effectlabel_2.setFont(font)
        self.effectlabel_2.setObjectName(_fromUtf8("effectlabel_2"))
        self.inputarmor = QtGui.QSpinBox(self.damageBox)
        self.inputarmor.setGeometry(QtCore.QRect(70, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputarmor.setFont(font)
        self.inputarmor.setAlignment(QtCore.Qt.AlignCenter)
        self.inputarmor.setMaximum(9999)
        self.inputarmor.setObjectName(_fromUtf8("inputarmor"))
        self.armorAmountlabel = QtGui.QLabel(self.damageBox)
        self.armorAmountlabel.setGeometry(QtCore.QRect(80, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.armorAmountlabel.setFont(font)
        self.armorAmountlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.armorAmountlabel.setObjectName(_fromUtf8("armorAmountlabel"))
        self.clearDamage_Button = QtGui.QPushButton(self.damageBox)
        self.clearDamage_Button.setGeometry(QtCore.QRect(10, 20, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearDamage_Button.setFont(font)
        self.clearDamage_Button.setObjectName(_fromUtf8("clearDamage_Button"))
        self.apAmountlabel = QtGui.QLabel(self.damageBox)
        self.apAmountlabel.setGeometry(QtCore.QRect(330, 10, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.apAmountlabel.setFont(font)
        self.apAmountlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apAmountlabel.setObjectName(_fromUtf8("apAmountlabel"))
        self.inputap = QtGui.QSpinBox(self.damageBox)
        self.inputap.setGeometry(QtCore.QRect(330, 30, 42, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputap.setFont(font)
        self.inputap.setAlignment(QtCore.Qt.AlignCenter)
        self.inputap.setMaximum(999)
        self.inputap.setObjectName(_fromUtf8("inputap"))
        self.selCover = QtGui.QComboBox(self.damageBox)
        self.selCover.setGeometry(QtCore.QRect(150, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selCover.setFont(font)
        self.selCover.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selCover.setEditable(False)
        self.selCover.setMaxVisibleItems(7)
        self.selCover.setMaxCount(7)
        self.selCover.setMinimumContentsLength(0)
        self.selCover.setObjectName(_fromUtf8("selCover"))
        self.coverlable = QtGui.QLabel(self.damageBox)
        self.coverlable.setGeometry(QtCore.QRect(210, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coverlable.setFont(font)
        self.coverlable.setAlignment(QtCore.Qt.AlignCenter)
        self.coverlable.setObjectName(_fromUtf8("coverlable"))
        self.plus_sign_6 = QtGui.QLabel(self.damageBox)
        self.plus_sign_6.setGeometry(QtCore.QRect(130, 40, 16, 16))
        self.plus_sign_6.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_6.setObjectName(_fromUtf8("plus_sign_6"))
        self.clearAll_Button = QtGui.QPushButton(self.centralwidget)
        self.clearAll_Button.setGeometry(QtCore.QRect(690, 300, 111, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.clearAll_Button.setFont(font)
        self.clearAll_Button.setObjectName(_fromUtf8("clearAll_Button"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName(_fromUtf8("menuAction"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAudio = QtGui.QMenu(self.menuSettings)
        self.menuAudio.setStatusTip(_fromUtf8(""))
        self.menuAudio.setObjectName(_fromUtf8("menuAudio"))
        self.menuDice = QtGui.QMenu(self.menuSettings)
        self.menuDice.setObjectName(_fromUtf8("menuDice"))
        self.menuWeb = QtGui.QMenu(self.menubar)
        self.menuWeb.setObjectName(_fromUtf8("menuWeb"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionRoll_2D = QtGui.QAction(MainWindow)
        self.actionRoll_2D.setObjectName(_fromUtf8("actionRoll_2D"))
        self.action_ClearAll = QtGui.QAction(MainWindow)
        self.action_ClearAll.setObjectName(_fromUtf8("action_ClearAll"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPlaySample = QtGui.QAction(MainWindow)
        self.actionPlaySample.setEnabled(False)
        self.actionPlaySample.setObjectName(_fromUtf8("actionPlaySample"))
        self.actionUnMute = QtGui.QAction(MainWindow)
        self.actionUnMute.setObjectName(_fromUtf8("actionUnMute"))
        self.actionMute = QtGui.QAction(MainWindow)
        self.actionMute.setObjectName(_fromUtf8("actionMute"))
        self.actionVisit_Blog = QtGui.QAction(MainWindow)
        self.actionVisit_Blog.setObjectName(_fromUtf8("actionVisit_Blog"))
        self.actionFeedback = QtGui.QAction(MainWindow)
        self.actionFeedback.setObjectName(_fromUtf8("actionFeedback"))
        self.actionOverview = QtGui.QAction(MainWindow)
        self.actionOverview.setObjectName(_fromUtf8("actionOverview"))
        self.actionAbout_TravCalc = QtGui.QAction(MainWindow)
        self.actionAbout_TravCalc.setObjectName(_fromUtf8("actionAbout_TravCalc"))
        self.actionRoll_Bane = QtGui.QAction(MainWindow)
        self.actionRoll_Bane.setObjectName(_fromUtf8("actionRoll_Bane"))
        self.actionRoll_Boon = QtGui.QAction(MainWindow)
        self.actionRoll_Boon.setObjectName(_fromUtf8("actionRoll_Boon"))
        self.actionStandardDice = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/die3_6s.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStandardDice.setIcon(icon1)
        self.actionStandardDice.setObjectName(_fromUtf8("actionStandardDice"))
        self.actionTravellerDice = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/die1_6t.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTravellerDice.setIcon(icon2)
        self.actionTravellerDice.setObjectName(_fromUtf8("actionTravellerDice"))
        self.actionAKODice = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/die1_6a.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAKODice.setIcon(icon3)
        self.actionAKODice.setObjectName(_fromUtf8("actionAKODice"))
        self.actionMetalDice = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/die1_6m.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMetalDice.setIcon(icon4)
        self.actionMetalDice.setObjectName(_fromUtf8("actionMetalDice"))
        self.actionMaleVoice = QtGui.QAction(MainWindow)
        self.actionMaleVoice.setEnabled(True)
        self.actionMaleVoice.setObjectName(_fromUtf8("actionMaleVoice"))
        self.actionFemaleVoice = QtGui.QAction(MainWindow)
        self.actionFemaleVoice.setEnabled(True)
        self.actionFemaleVoice.setObjectName(_fromUtf8("actionFemaleVoice"))
        self.actionRobotVoice = QtGui.QAction(MainWindow)
        self.actionRobotVoice.setObjectName(_fromUtf8("actionRobotVoice"))
        self.action_ClearDamage = QtGui.QAction(MainWindow)
        self.action_ClearDamage.setObjectName(_fromUtf8("action_ClearDamage"))
        self.actionCUBBLEDice = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/die1_6c.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCUBBLEDice.setIcon(icon5)
        self.actionCUBBLEDice.setObjectName(_fromUtf8("actionCUBBLEDice"))
        self.actionRomanDice = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/die1_6r.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRomanDice.setIcon(icon6)
        self.actionRomanDice.setObjectName(_fromUtf8("actionRomanDice"))
        self.actionRoll_D66 = QtGui.QAction(MainWindow)
        self.actionRoll_D66.setObjectName(_fromUtf8("actionRoll_D66"))
        self.actionGridGrooveDice = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/die1_6g.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGridGrooveDice.setIcon(icon7)
        self.actionGridGrooveDice.setObjectName(_fromUtf8("actionGridGrooveDice"))
        self.actionMixedDice = QtGui.QAction(MainWindow)
        self.actionMixedDice.setObjectName(_fromUtf8("actionMixedDice"))
        self.actionQuestionDice = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/die2_1q.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuestionDice.setIcon(icon8)
        self.actionQuestionDice.setObjectName(_fromUtf8("actionQuestionDice"))
        self.menuAction.addAction(self.actionRoll_2D)
        self.menuAction.addAction(self.actionRoll_Boon)
        self.menuAction.addAction(self.actionRoll_Bane)
        self.menuAction.addAction(self.actionRoll_D66)
        self.menuAction.addAction(self.action_ClearAll)
        self.menuAction.addAction(self.action_ClearDamage)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionQuit)
        self.menuAudio.addAction(self.actionMute)
        self.menuAudio.addAction(self.actionMaleVoice)
        self.menuAudio.addAction(self.actionFemaleVoice)
        self.menuAudio.addAction(self.actionRobotVoice)
        self.menuAudio.addAction(self.actionPlaySample)
        self.menuDice.addAction(self.actionStandardDice)
        self.menuDice.addAction(self.actionTravellerDice)
        self.menuDice.addAction(self.actionAKODice)
        self.menuDice.addAction(self.actionMetalDice)
        self.menuDice.addAction(self.actionCUBBLEDice)
        self.menuDice.addAction(self.actionRomanDice)
        self.menuDice.addAction(self.actionGridGrooveDice)
        self.menuDice.addSeparator()
        self.menuDice.addAction(self.actionMixedDice)
        self.menuDice.addSeparator()
        self.menuDice.addAction(self.actionQuestionDice)
        self.menuSettings.addAction(self.menuDice.menuAction())
        self.menuSettings.addAction(self.menuAudio.menuAction())
        self.menuWeb.addAction(self.actionVisit_Blog)
        self.menuWeb.addAction(self.actionFeedback)
        self.menuHelp.addAction(self.actionOverview)
        self.menuHelp.addAction(self.actionAbout_TravCalc)
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWeb.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.selDiff.setCurrentIndex(-1)
        self.selTimeframe.setCurrentIndex(-1)
        self.selNewTimeframe.setCurrentIndex(-1)
        self.selCover.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.selDiff, self.inputtasks)
        MainWindow.setTabOrder(self.inputtasks, self.selTimeframe)
        MainWindow.setTabOrder(self.selTimeframe, self.selNewTimeframe)
        MainWindow.setTabOrder(self.selNewTimeframe, self.inputchar)
        MainWindow.setTabOrder(self.inputchar, self.inputlevel)
        MainWindow.setTabOrder(self.inputlevel, self.inputDM)
        MainWindow.setTabOrder(self.inputDM, self.selChained)
        MainWindow.setTabOrder(self.selChained, self.roll2D_Button)
        MainWindow.setTabOrder(self.roll2D_Button, self.rollBoon_Button)
        MainWindow.setTabOrder(self.rollBoon_Button, self.rollBane_Button)
        MainWindow.setTabOrder(self.rollBane_Button, self.rollD66_Button)
        MainWindow.setTabOrder(self.rollD66_Button, self.clearDamage_Button)
        MainWindow.setTabOrder(self.clearDamage_Button, self.inputarmor)
        MainWindow.setTabOrder(self.inputarmor, self.selCover)
        MainWindow.setTabOrder(self.selCover, self.inputap)
        MainWindow.setTabOrder(self.inputap, self.inputdice)
        MainWindow.setTabOrder(self.inputdice, self.damage_Button)
        MainWindow.setTabOrder(self.damage_Button, self.destructive_Button)
        MainWindow.setTabOrder(self.destructive_Button, self.inputDamageDM)
        MainWindow.setTabOrder(self.inputDamageDM, self.clearAll_Button)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TravCalc 3.0.6 (Beta)", None, QtGui.QApplication.UnicodeUTF8))
        self.taskBox.setTitle(QtGui.QApplication.translate("MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.effectlabel.setText(QtGui.QApplication.translate("MainWindow", "Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.effect_result.setToolTip(QtGui.QApplication.translate("MainWindow", "Task effect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("MainWindow", "Characteristic", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign_2.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.equal_sign.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.resultlabel.setText(QtGui.QApplication.translate("MainWindow", "Roll Result", None, QtGui.QApplication.UnicodeUTF8))
        self.totalDM.setToolTip(QtGui.QApplication.translate("MainWindow", "Dice modifier total", None, QtGui.QApplication.UnicodeUTF8))
        self.totalDM.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.inputDM.setToolTip(QtGui.QApplication.translate("MainWindow", "Added dice modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.inputchar.setToolTip(QtGui.QApplication.translate("MainWindow", "Characteristic", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign_1.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.inputlevel.setToolTip(QtGui.QApplication.translate("MainWindow", "Level of skill", None, QtGui.QApplication.UnicodeUTF8))
        self.die1Label.setStatusTip(QtGui.QApplication.translate("MainWindow", "First die", None, QtGui.QApplication.UnicodeUTF8))
        self.die3Label.setStatusTip(QtGui.QApplication.translate("MainWindow", "Third die", None, QtGui.QApplication.UnicodeUTF8))
        self.die2Label.setStatusTip(QtGui.QApplication.translate("MainWindow", "Second die", None, QtGui.QApplication.UnicodeUTF8))
        self.rollBox.setTitle(QtGui.QApplication.translate("MainWindow", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.roll2D_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "Make a 2D roll", None, QtGui.QApplication.UnicodeUTF8))
        self.roll2D_Button.setText(QtGui.QApplication.translate("MainWindow", "2D", None, QtGui.QApplication.UnicodeUTF8))
        self.rollBoon_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "Make a Boon roll", None, QtGui.QApplication.UnicodeUTF8))
        self.rollBoon_Button.setText(QtGui.QApplication.translate("MainWindow", "Boon", None, QtGui.QApplication.UnicodeUTF8))
        self.rollBane_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "Make a Bane roll", None, QtGui.QApplication.UnicodeUTF8))
        self.rollBane_Button.setText(QtGui.QApplication.translate("MainWindow", "Bane", None, QtGui.QApplication.UnicodeUTF8))
        self.rollD66_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "Make a D66 roll", None, QtGui.QApplication.UnicodeUTF8))
        self.rollD66_Button.setText(QtGui.QApplication.translate("MainWindow", "D66", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign_5.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.chainedDM.setToolTip(QtGui.QApplication.translate("MainWindow", "Task Chained DM", None, QtGui.QApplication.UnicodeUTF8))
        self.charmod.setToolTip(QtGui.QApplication.translate("MainWindow", "Characteristic Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.charmod.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.selChained.setToolTip(QtGui.QApplication.translate("MainWindow", "Chained task?", None, QtGui.QApplication.UnicodeUTF8))
        self.difflabel.setText(QtGui.QApplication.translate("MainWindow", "Task Difficulty", None, QtGui.QApplication.UnicodeUTF8))
        self.selDiff.setToolTip(QtGui.QApplication.translate("MainWindow", "Select Difficulty", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtasks.setToolTip(QtGui.QApplication.translate("MainWindow", "Number of Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.numTasksLabel.setText(QtGui.QApplication.translate("MainWindow", "No. of Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.selTimeframe.setToolTip(QtGui.QApplication.translate("MainWindow", "Select Timeframe", None, QtGui.QApplication.UnicodeUTF8))
        self.selNewTimeframe.setToolTip(QtGui.QApplication.translate("MainWindow", "Updated Timeframe", None, QtGui.QApplication.UnicodeUTF8))
        self.timeframeLabel_1.setText(QtGui.QApplication.translate("MainWindow", "Timeframe", None, QtGui.QApplication.UnicodeUTF8))
        self.timeframeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "New Timeframe", None, QtGui.QApplication.UnicodeUTF8))
        self.tasktimeLabel.setText(QtGui.QApplication.translate("MainWindow", "Task Time", None, QtGui.QApplication.UnicodeUTF8))
        self.tasktime_result.setToolTip(QtGui.QApplication.translate("MainWindow", "Time to perform task", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Mod", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Skill Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "DM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Chained DM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.rollresult.setToolTip(QtGui.QApplication.translate("MainWindow", "Total roll result", None, QtGui.QApplication.UnicodeUTF8))
        self.outcomeBox.setTitle(QtGui.QApplication.translate("MainWindow", "Outcome", None, QtGui.QApplication.UnicodeUTF8))
        self.damageBox.setTitle(QtGui.QApplication.translate("MainWindow", "Damage", None, QtGui.QApplication.UnicodeUTF8))
        self.inputdice.setToolTip(QtGui.QApplication.translate("MainWindow", "Number of dice", None, QtGui.QApplication.UnicodeUTF8))
        self.Dicelabel.setText(QtGui.QApplication.translate("MainWindow", "Dice", None, QtGui.QApplication.UnicodeUTF8))
        self.damage_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "Normal damage", None, QtGui.QApplication.UnicodeUTF8))
        self.damage_Button.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.destructive_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "Destructive damage", None, QtGui.QApplication.UnicodeUTF8))
        self.destructive_Button.setText(QtGui.QApplication.translate("MainWindow", "DD", None, QtGui.QApplication.UnicodeUTF8))
        self.inputDamageDM.setToolTip(QtGui.QApplication.translate("MainWindow", "Added dice modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign_3.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.damageDMlabel.setText(QtGui.QApplication.translate("MainWindow", "DM", None, QtGui.QApplication.UnicodeUTF8))
        self.totalDamagelabel.setText(QtGui.QApplication.translate("MainWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.totalDamage.setToolTip(QtGui.QApplication.translate("MainWindow", "Total damage", None, QtGui.QApplication.UnicodeUTF8))
        self.effect_damage.setToolTip(QtGui.QApplication.translate("MainWindow", "Task effect", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign_4.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.effectlabel_2.setText(QtGui.QApplication.translate("MainWindow", "Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.inputarmor.setToolTip(QtGui.QApplication.translate("MainWindow", "Armor score", None, QtGui.QApplication.UnicodeUTF8))
        self.armorAmountlabel.setText(QtGui.QApplication.translate("MainWindow", " Armor", None, QtGui.QApplication.UnicodeUTF8))
        self.clearDamage_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear Damage fields", None, QtGui.QApplication.UnicodeUTF8))
        self.clearDamage_Button.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.apAmountlabel.setText(QtGui.QApplication.translate("MainWindow", "    AP", None, QtGui.QApplication.UnicodeUTF8))
        self.inputap.setToolTip(QtGui.QApplication.translate("MainWindow", "AP score", None, QtGui.QApplication.UnicodeUTF8))
        self.selCover.setToolTip(QtGui.QApplication.translate("MainWindow", "Select Difficulty", None, QtGui.QApplication.UnicodeUTF8))
        self.coverlable.setText(QtGui.QApplication.translate("MainWindow", "Cover", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign_6.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAll_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear all fields", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAll_Button.setText(QtGui.QApplication.translate("MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAction.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAudio.setTitle(QtGui.QApplication.translate("MainWindow", "Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDice.setTitle(QtGui.QApplication.translate("MainWindow", "Dice", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWeb.setTitle(QtGui.QApplication.translate("MainWindow", "Web", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll_2D.setText(QtGui.QApplication.translate("MainWindow", "2D Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll_2D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Make a 2D roll", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ClearAll.setText(QtGui.QApplication.translate("MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ClearAll.setStatusTip(QtGui.QApplication.translate("MainWindow", "Clear all fields", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quit this program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlaySample.setText(QtGui.QApplication.translate("MainWindow", "Play Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlaySample.setStatusTip(QtGui.QApplication.translate("MainWindow", "Perform an audio test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnMute.setText(QtGui.QApplication.translate("MainWindow", "Un-Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnMute.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enable audio", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMute.setText(QtGui.QApplication.translate("MainWindow", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMute.setStatusTip(QtGui.QApplication.translate("MainWindow", "Disable audio", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVisit_Blog.setText(QtGui.QApplication.translate("MainWindow", "Visit Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVisit_Blog.setToolTip(QtGui.QApplication.translate("MainWindow", "Visit Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVisit_Blog.setStatusTip(QtGui.QApplication.translate("MainWindow", "Visit Shawn\'s blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFeedback.setText(QtGui.QApplication.translate("MainWindow", "Give Feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFeedback.setIconText(QtGui.QApplication.translate("MainWindow", "Give me your feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFeedback.setToolTip(QtGui.QApplication.translate("MainWindow", "Give me your feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFeedback.setStatusTip(QtGui.QApplication.translate("MainWindow", "Give me your feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOverview.setText(QtGui.QApplication.translate("MainWindow", "Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOverview.setStatusTip(QtGui.QApplication.translate("MainWindow", "Give an overview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_TravCalc.setText(QtGui.QApplication.translate("MainWindow", "About TravCalc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_TravCalc.setStatusTip(QtGui.QApplication.translate("MainWindow", "About TravCalc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll_Bane.setText(QtGui.QApplication.translate("MainWindow", "Bane Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll_Bane.setStatusTip(QtGui.QApplication.translate("MainWindow", "Make a Bane roll", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll_Boon.setText(QtGui.QApplication.translate("MainWindow", "Boon Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll_Boon.setStatusTip(QtGui.QApplication.translate("MainWindow", "Make a Boon roll", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStandardDice.setText(QtGui.QApplication.translate("MainWindow", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStandardDice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use standard dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTravellerDice.setText(QtGui.QApplication.translate("MainWindow", "Traveller", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTravellerDice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use Traveller dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAKODice.setText(QtGui.QApplication.translate("MainWindow", "AKO", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAKODice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use AKO Dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMetalDice.setText(QtGui.QApplication.translate("MainWindow", "Metal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMetalDice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use metal dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaleVoice.setText(QtGui.QApplication.translate("MainWindow", "Use male voice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaleVoice.setStatusTip(QtGui.QApplication.translate("MainWindow", "This program will speak with a male voice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFemaleVoice.setText(QtGui.QApplication.translate("MainWindow", "Use female voice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFemaleVoice.setStatusTip(QtGui.QApplication.translate("MainWindow", "This program will speak with a female voice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRobotVoice.setText(QtGui.QApplication.translate("MainWindow", "Use robot voice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRobotVoice.setStatusTip(QtGui.QApplication.translate("MainWindow", "This program will speak with a robot voice", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ClearDamage.setText(QtGui.QApplication.translate("MainWindow", "Clear Damage", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ClearDamage.setStatusTip(QtGui.QApplication.translate("MainWindow", "Clear Damage fields", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCUBBLEDice.setText(QtGui.QApplication.translate("MainWindow", "CUBBLE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCUBBLEDice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use CUBBLE Dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRomanDice.setText(QtGui.QApplication.translate("MainWindow", "Roman", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRomanDice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use Roman dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll_D66.setText(QtGui.QApplication.translate("MainWindow", "D66 Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll_D66.setStatusTip(QtGui.QApplication.translate("MainWindow", "Make a D66 roll", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGridGrooveDice.setText(QtGui.QApplication.translate("MainWindow", "Grid Groove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGridGrooveDice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use Grid Groove dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMixedDice.setText(QtGui.QApplication.translate("MainWindow", "Mixed Dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuestionDice.setText(QtGui.QApplication.translate("MainWindow", "Question Dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuestionDice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use Question Dice", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
import travcalc_306b_rc
